name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/@checkout@v2
      -name: Run Django unit test
      run: pip install --user Django
        python manage.py test
